apiVersion: v1
kind: Pod
metadata:
  name: conv-app
  labels:
    app: conv-app
spec:
  containers:
    - name: conv-app
      image: antonlarichev/conv-app:1.0
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"